name: Add Issues to Project

on:
  issues:
    types: [closed]
jobs:
  Add_Closed_Issue_To_Project:
    runs-on: ubuntu-latest
    steps:
    - uses: konradpabjan/actions-add-new-issue-to-column@v1.1
      with:
        action-token: "${{ secrets.github_actions2 }}"
        project-url: "https://github.com/depadiernos/deploy-id-test/projects/1"
        column-name: "test"
